### PR TITLE
fix: track duration dropdown fixed

### LINKED ISSUE #625: Not all durations are showing per track
If you call 
`/tracks/5dZCRQnJ75PN1aB4`
(Which is the track called "Anxiety")
You can see 3 guides in the response, with 4 mp3 in total. 1 for Will, 1 for Steven and 2 for Regina. However the app only shows one option per guide. The one from Regina with id `FP5Kmz2LWvh87n0L` is missing. 

It seems that the issue also happens for other tracks, like `zHNJ1zL04PMAxzRF`. I suppose the UI doesn't display all the options per guide (note that each guide can have different durations)

### PR DESCRIPTION
**Pull request by osamaasifoak**
[Not all durations are showing per track#625](https://github.com/meditohq/medito-app/issues/625)

### CODE REVIEW

File: lib/views/track/track_view.dart [hunk 1]
```diff
@@ -90,11 +90,15 @@ class _TrackViewState extends ConsumerState<TrackView>
...
-    unawaited(context.push(RouteConstants.playerPath));
+    try {
+      await ref.read(playerProvider.notifier).loadSelectedTrack(
+            trackModel: trackModel,
+            file: file,
+          );
+      unawaited(context.push(RouteConstants.playerPath));
+    } catch (e) {
+      print(e);
+    }
```
Comment (michaelcspeed) [inline lib/views/track/track_view.dart]: Why are we just swallowing this exception? What kind of exception might we expect?

File: lib/views/track/track_view.dart [hunk 2]
```diff
@@ -268,16 +267,16 @@ class _TrackViewState extends ConsumerState<TrackView>
       topRight: 7,
       bottomRight: 7,
       bottomLeft: 7,
-      isDisabled: audioFiles.length > 1,
+      isDisabled: (_selectedFile ?? audioFiles).length > 1,
```
Comment (michaelcspeed) [inline lib/views/track/track_view.dart]: can remove the _

File: lib/views/track/track_view.dart (hunk 1 above)
Comment (osamaasifoak) [reply lib/views/track/track_view.dart]: I apologize for adding this block; it was only for testing purposes.
