### PR TITLE
fix: bottom sheet issues fixed

### LINKED ISSUE #573: Track screen UI refresh
1. **Screen is now a bottom sheet:**
   - Replace track screen by a bottom sheet. See design here:
[https://www.figma.com/file/E9k4sKjlBDUREveJbUtf4A/Medito-2023?type=design&node-id=2300%3A6790&mode=design&t=jBGq5ZOIlloVCPSl-1](https://www.figma.com/file/E9k4sKjlBDUREveJbUtf4A/Medito-2023?type=design&node-id=2300%3A6790&mode=design&t=jBGq5ZOIlloVCPSl-1
)
2. **Bottom sheet has the right border radius:**

3. **Text fields open a material menu:**
   - Use text field for the text button
   - For the menu, use the menuAnchor to show the material menu when the text field is tapped.
   - Material design guidelines for menus: [Material Menus](https://m3.material.io/components/menus/overview)
   - Material design guidelines for text fields: [Material Text Fields](https://m3.material.io/components/text-fields/overview)

4. **Text fields / menu dynamically change based on the selected value of the other menu:**
   - When the selected value changes, update the options of the other menu accordingly.

5. **Text fields don't have a menu option when there is a single option:**
   - Check the length of the options for each text field. If there's only one option, don't show the menu.

6. **Play button opens the big player:**
   - Open big player when tapping on play button 

7. **The mini player is behind the bottom sheet:**
   - The bottom sheet is first.

### PR DESCRIPTION
**Pull request by osamaasifoak**
[Track screen UI refresh#573](https://github.com/meditohq/medito-app/issues/573)

### CODE REVIEW

File: lib/widgets/drop_down_widget.dart [hunk 1]
```diff
@@ -21,6 +23,8 @@ class DropdownWidget<T> extends StatelessWidget {
   final double topRight;
   final double bottomLeft;
   final double bottomRight;
+  final bool disabled;
```
Comment (michaelcspeed) [inline lib/widgets/drop_down_widget.dart]: Remember Booleans should be named as affirmative statements isDisabled/isEnabled

**Review by michaelcspeed — COMMENTED** [review]
Just one thing to change and you can merge it @osamaasifoak

File: lib/widgets/drop_down_widget.dart (hunk 1 above)
Comment (osamaasifoak) [reply lib/widgets/drop_down_widget.dart]: Noted!
