### PR TITLE
fix: fade effect added on bg sound

### LINKED ISSUE #557: Make background sound fade out at the end of a track
If background sound is on, we should make it fade out (slowly go from current volume to 0) when the track is about to end. It should only be applied to the background sound.
The previous app had this behaviour. Feel free to ask Mike if you need more info. 
Thank you!

### PR DESCRIPTION
**Pull request by osamaasifoak**
[Make background sound fade out at the end of a track#557](https://github.com/meditohq/medito-app/issues/557)

### CODE REVIEW

File: lib/providers/player/audio_player_provider.dart [hunk 1]
```diff
@@ -22,7 +22,8 @@ class AudioPlayerNotifier extends BaseAudioHandler
   TrackFilesModel? currentlyPlayingTrack;
   final hasBgSound = 'hasBgSound';
   final trackAudioPlayer = AudioPlayer();
-
+  final fade_duration = 5;
```
Comment (michaelcspeed) [inline lib/providers/player/audio_player_provider.dart]: This should be lowerCamelCase shouldn't it?

**Review by michaelcspeed — CHANGES_REQUESTED** [review]
Just checking, if you start a new session or move the player to a point somewhere in the night of the session after a fade has started, is the volume reset to normal?

**Comment by osamaasifoak** [comment]
Yes, it will reset to its original state.
